server:
  port: 8080

spring:
  application:
    name: ioma-mcp-service


spring.ai.mcp.server:  # 配置类 McpServerStreamableHttpProperties
  name: ioma-dg-mcp-server
  version: 1.0.0
  type: SYNC
  capabilities:
    tool: true
    resource: true
    prompt: true
    completion: true
  # 使用什么protocol
  # STATELESS #必须设置为 STATELESS 才能启用无状态服务器
  protocol: STREAMABLE #必须设置为 STREAMABLE 以启用流式服务器

  # Streamable-HTTP特有配置
  streamable-http:
    mcp-endpoint: /mcp
    keep-alive-interval: 30s # 连接保活,表示每 30 秒发送一次心跳包


mcp:
  api:
    validApiKeys:
      - apikey%1111
      - apikey%2222

#log
logging:
  file:
    name: ./logs/${spring.application.name}.log # 日志文件名，全路径

