spring:
  ai:
    openai:
      base-url: https://api.moonshot.cn  #配置chat的ak
      api-key: sk-
      chat:
        completions-path: /v1/chat/completions #配置chant的接口路径
        options:
          model: kimi-k2-0905-preview
          temperature: 0.6
    mcp:
      client:
        name: ai-demo
        type: SYNC
        request-timeout: 30000
        enabled: true
        toolcallback:
          enabled: true
        sse:
          connections:
            server1:
              url: https://mcp-09724909-442f-4b85.api-inference.modelscope.cn
